extends: airbnb-base
parserOptions:
  sourceType: script
  ecmaVersion: latest
rules:
  valid-jsdoc:
    - error
    - requireReturn: false
      requireReturnDescription: false
      preferType:
        String: string
        Number: number
        Boolean: boolean
        Function: function
        object: Object
        date: Date
        error: Error
      prefer:
        return: returns
  strict:
    - error
    - safe
  linebreak-style: 'off'
  no-restricted-syntax:
    - 'off'
  no-await-in-loop: 'off'
  import/no-unresolved: 0
  class-methods-use-this: 'off'
  no-promise-executor-return: 'off'
