plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - assets:
        - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - package.json
        - CHANGELOG.md
        - app.min.js
branches: master
